### ISSUE TITLE
Exception: Added StorageOpen to entity while resetting predicted entities

### ISSUE THREAD

**Issue by ShadowCommander** [RMC-14/RMC-14#2599]
## Description

```
[ERRO] state: Added component StorageOpen to entity Marine technician welderpack (17915/n2025301, CMBackpackWelder) while resetting predicted entities.
Stack trace:
   at System.Environment.get_StackTrace()
   at Robust.Shared.GameObjects.EntityManager.AddComponentInternal[T](EntityUid uid, T component, ComponentRegistration reg, Boolean overwrite, Boolean skipInit, MetaDataComponent metadata) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 341
   at Robust.Shared.GameObjects.EntityManager.AddComponentInternal[T](EntityUid uid, T component, Boolean overwrite, Boolean skipInit, MetaDataComponent metadata) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 325
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid, T component, Boolean overwrite, MetaDataComponent metadata) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 303
   at Robust.Shared.GameObjects.EntityManager.AddComponent[T](EntityUid uid) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityManager.Components.cs:line 241
   at Content.Shared._RMC14.Storage.CMStorageSystem.OnCloseOnMoveUIOpened(Entity`1 ent, BoundUIOpenedEvent& args) in /home/runner/work/RMC-14/RMC-14/Content.Shared/_RMC14/Storage/CMStorageSystem.cs:line 150
   at Robust.Shared.GameObjects.BoundUserInterfaceRegisterExt.Subscriber`1.<>c__DisplayClass4_0`1.<Event>b__0(Entity`1 ent, TEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Components/UserInterface/BoundUserInterfaceRegisterExt.cs:line 89
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 324
   at Robust.Shared.GameObjects.EntityEventBus.EntDispatch(EntityUid euid, Type eventType, Unit& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 633
   at Robust.Shared.GameObjects.EntityEventBus.RaiseLocalEvent[TEvent](EntityUid uid, TEvent args, Boolean broadcast) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 200
   at Robust.Shared.GameObjects.SharedUserInterfaceSystem.OpenUiInternal(Entity`1 ent, Enum key, EntityUid actor) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedUserInterfaceSystem.cs:line 250
   at Robust.Shared.GameObjects.SharedUserInterfaceSystem.OnUserInterfaceHandleState(Entity`1 ent, ComponentHandleState& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/Systems/SharedUserInterfaceSystem.cs:line 344
   at Robust.Shared.GameObjects.EntityEventBus.<>c__DisplayClass57_0`2.<SubscribeLocalEvent>g__EventHandler|0(EntityUid uid, IComponent comp, TEvent& args) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/GameObjects/EntityEventBus.Directed.cs:line 324
   at Robust.Client.GameStates.ClientGameStateManager.ResetPredictedEntities() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 606
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 338
   at Robust.Client.GameController.Tick(FrameEventArgs frameEventArgs) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.cs:line 535
   at Robust.Shared.Timing.GameLoop.Run() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Shared/Timing/GameLoop.cs:line 135
   at Robust.Client.GameController.ContinueStartupAndLoop(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 162
   at Robust.Client.GameController.GameThreadMain(DisplayMode mode) in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 147
   at Robust.Client.GameController.<>c__DisplayClass100_0.<Run>b__0() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameController/GameController.Standalone.cs:line 106
   at System.Threading.Thread.StartCallback()
[ERRO] runtime: Caught exception in "ResetPredictedEntities"
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at Robust.Client.GameStates.ClientGameStateManager.ResetPredictedEntities() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 571
   at Robust.Client.GameStates.ClientGameStateManager.ApplyGameState() in /home/runner/work/RobustToolbox/RobustToolbox/Robust.Client/GameStates/ClientGameStateManager.cs:line 338
```

**Reproduction**

**Screenshots**

**Additional context**

**Comment by Vermidia** [comment]
Fixed?
