### ISSUE TITLE
Firing an incendiary slug crashes the server in debug mode

### ISSUE THREAD

**Issue by CyberTropic** [RMC-14/RMC-14#4038]
## Description

Spawning in and firing an incendiary slug from a shotgun causes a hard crash on the debug server. Other shotgun shells work fine.
>[FATL] unhandled: Robust.Shared.Utility.DebugAssertException: Exception of type 'Robust.Shared.Utility.DebugAssertException' was thrown.
>at Robust.Shared.Utility.DebugTools.Assert(Boolean condition) in C:\\...\RMC-14\RobustToolbox\Robust.Shared\Utility\DebugTools.cs:line 37
   at Content.Server.Weapons.Ranged.Systems.GunSystem.LinearSpread(Angle start, Angle end, Int32 intervals) in C:\\...\RMC-14\Content.Server\Weapons\Ranged\Systems\GunSystem.cs:line 338
   at Content.Server.Weapons.Ranged.Systems.GunSystem.<Shoot>g__CreateAndFireProjectiles|28_0(EntityUid ammoEnt, AmmoComponent ammoComp, <>c__DisplayClass28_0&) in C:\\...\RMC-14\Content.Server\Weapons\Ranged\Systems\GunSystem.cs:line 285
   at Content.Server.Weapons.Ranged.Systems.GunSystem.Shoot(EntityUid gunUid, GunComponent gun, List`1 ammo, EntityCoordinates fromCoordinates, EntityCoordinates toCoordinates, Boolean& userImpulse, Nullable`1 user, Boolean throwItems) in C:\\...\RMC-14\Content.Server\Weapons\Ranged\Systems\GunSystem.cs:line 133
>...
>C:\\...\RMC-14\bin\Content.Server\Content.Server.exe (process 12268) exited with code -532462766 (0xe0434352).

**Reproduction**

Start a debug server, spawn in a box of incendiary slugs, load into a shotgun, and fire.

**Screenshots**

https://github.com/user-attachments/assets/a803283d-bc39-4f2f-bcd9-faf1da226b53

**Additional context**

Running on local debug server, production doesn't cause a crash.

**Comment by Vermidia** [comment]
This is because it has spread with a count of 1. Like the normal slug the fix is just to remove projectileSpread. Not really important since incendiary slugs aren't implemented yet.

**Comment by CyberTropic** [comment]
Incendiary ammo implemented
